FROM openjdk:11
LABEL authors="rebhi"
EXPOSE 8761
ADD target/Stock_bibliothèque_microservices-0.0.1-SNAPSHOT.jar Stock_bibliothèque_microservices.jar

ENTRYPOINT ["java", "-jar","Stock_bibliothèque_microservices.jar"]







